replicaCount: 1

image:
  repository: ghcr.io/callumkerredwards/library-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

jwt:
  secret:
    create: true
    annotations: {}
    name: ""
    signingKey:

mongodb:
  fromRelease:
    ## If enabled, the mongodb host is set to {{ .Release.Name }}{{ .Values.mongodb.inRelease.hostSuffix }}
    enable: false
    hostSuffix: "-mongodb"
  host:
  port: "27017"
  secret:
    create: true
    annotations: {}
    name: ""
    username:
    password:

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
