version: "3.8"

services:
  mongo:
    image: "mongo:5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - "27017:27017"
    networks:
      - backendstack
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 15s

  api:
    build: .
    image: "ghcr.io/callumkerredwards/library-api:development"
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "mongopwd"
      DB_HOST: "mongo"
      DB_PORT: "27017"
      JWT_SIGNING_KEY: "test-signing-key"
    depends_on:
      - mongo
    ports:
    - "8081:8080"
    networks:
      - backendstack

networks:
  backendstack:
    driver: bridge