version: "3.8"

services:
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks:
      - fullstack
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  api:
    build: server/
    image: "ghcr.io/callumkerredwards/library/server:development"
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "mongopwd"
      DB_HOST: "mongo"
      DB_PORT: "27017"
      JWT_SIGNING_KEY: "test-signing-key"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - fullstack

volumes:
  database_mongo:

networks:
  fullstack:
    driver: bridge
