version: "3"

tasks:
  gobuild:
    cmds:
      - go build -v ./...

  gotest:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  tidy:
    cmds:
      - go mod tidy

  gotest-e2e:
    cmds:
      - go test -tags=e2e -v ./...

  run:
    cmds:
      - docker compose up --build

  run-detached:
    cmds:
      - docker compose up --wait --build
  stop:
    cmds:
      - docker compose down

  conbuild:
    cmds:
      - docker compose build

  e2e-test:
    cmds:
      - task: run-detached
      - task: gotest-e2e
      - task: stop
