version: "3"

tasks:
  gobuild:
    cmds:
      - go build -v ./...

  gotest:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run
      - ct lint --chart-dirs helm/library-api --charts helm/library-api

  tidy:
    cmds:
      - go mod tidy

  gotest-e2e:
    cmds:
      - go test -tags=e2e,integration -v ./...
    env:
      DB_USERNAME: "root"
      DB_PASSWORD: "mongopwd"
      DB_HOST: "localhost"
      DB_PORT: "27017"

  run:
    cmds:
      - docker compose up --build

  run-detached:
    cmds:
      - docker compose up --wait --build
  stop:
    cmds:
      - docker compose down

  conbuild:
    cmds:
      - docker compose build

  e2e-test:
    cmds:
      - task: run-detached
      - task: gotest-e2e
      - task: stop

  integration-test:
    cmds:
      - docker compose up mongo --wait
      - go test -tags=integration -v ./...
    env:
      DB_USERNAME: "root"
      DB_PASSWORD: "mongopwd"
      DB_HOST: "localhost"
      DB_PORT: "27017"
