version: '3'

tasks:
  gobuild:
    dir: server
    cmds:
      - go build -v ./... 
  
  gotest:
    dir: server
    cmds:
      - go test -v ./...

  lint:
    dir: server
    cmds:
      - golangci-lint run

  tidy:
    dir: server
    cmds:
      - go mod tidy

  gotest-e2e:
    dir: server
    cmds:
      - go test -tags=e2e -v ./...
  
  run:
    cmds:
      - docker compose up --build

  run-detached:
    cmds:
      - docker compose up --wait --build
  stop:
    cmds:
      - docker compose down
  
  conbuild:
    cmds:
      - docker compose build

  e2e-test:
    cmds:
      - task: run-detached
      - task: gotest-e2e
      - task: stop

  client-start:
    dir: client
    cmds:
      - npm run serve
