{{- if .Values.mongodb.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-api.databaseSecretName" . }}
type: Opaque
data:
  username: {{ .Values.mongodb.secret.username | b64enc }}
  password: {{ .Values.mongodb.secret.password | b64enc }}
{{- end }}